#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdlib.h>
#include <signal.h>
#include <sys/stat.h>

#define SIGINT  2 				// Defines the signal no.
char process[5];

/*-----------------------------------------------Signal-Handler-Function()-------------------------------------------*/
void handle_sigint(int sig) 
{
	/*
		Objective:			To handle signal generated by using command "Ctrl+C". This signal indicates that
							process has completed the execution of system call and wants to unlock the buffer.
		Return Type:		void(null)
		Parameter:		
			integer sig:	determines the signal no.
		Approach:			Value of unlocked buffer and process is stored using pipes, so that information can
							be transfered from one this process to another.
	*/

	char ans;
    printf("\n Caught System call completion signal.");
    printf("\n Unlocking Buffer.");
	printf("\n");

	int fd;
    char * myfifo = "/tmp/myfifo";

    /* create the FIFO (named pipe) */
    mkfifo(myfifo, 0666);

    /* write process number to the FIFO */
    fd = open(myfifo, O_WRONLY);
    write(fd, process, sizeof(process));
    close(fd);

	sleep(8);
	exit(0);
} 

/*-------------------------------------------------Controller-Function()---------------------------------------------*/
 void controller() {
	/*
		Objective:		It defines how the process will handle the signal to come out of indefinite looping
						(sleeping).
	*/
	signal(SIGINT,handle_sigint); 
    while (1) 
    { 
        printf("Executing System Call.\n"); 
        sleep(1); 
    } 
}

/*----------------------------------------------------Main-Function()------------------------------------------------*/
int main(int argc, char const *argv[]) {
	/*
		Objective:		It allows process to enter into indefinite looping/sleeping.
	*/

	if (argc != 2)
		exit(0);
	
	strcpy(process, argv[1]);
	char proc[100];	
	strcpy(proc, "\e]2;");
	strcat(proc,"System call Execution of Process: ");
	strcat(proc,argv[1]);
	strcat(proc,"\a");
	printf("%s",proc);
	controller();

	return 0;
}
/*-------------------------------------------------------------------------------------------------------------------*/